language: ruby
rvm:
- 2.6.0
script:
script:
  - bundle exec rails db:setup
  - bundle exec rails spec
cache: bundler
services:
  - postgresql
before_script:
  - psql -c 'create database taskdemo_test;' -U postgres 